## spring boot 3.0 可以不采用bootstrap.xml 即可启动并且找到注册中心 减少多余依赖（依赖spring cloud的）
spring:
  application:
    name: last-cloud
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:classpath:test.yml
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        file-extension: yml
    loadbalancer:
      eager-load:
        clients:
          - xxx-service