spring:
  application:
    name: last-cloud
nacos:
  server:
    aaLong: "{a : 'b'}" # value使用map必须使用这种, @Value不建议复杂类型, 建议使用@ConfigurationProperties
---
## spring boot 3.0 可以不采用bootstrap.xml 即可启动并且找到注册中心 减少多余依赖（依赖spring cloud的）
spring:
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:classpath:test.yml
      # 非optional方式获取配置, 如果失败则会影响spring启动(必要配置时).
      - nacos:test.yml
    # 3.0 版本 分文件块的方式支持多环境配置
    activate:
      on-profile: test
  cloud:
    nacos:
#      server-addr: "[::]:8848"
      config:
        file-extension: yml
    loadbalancer:
      eager-load:
        clients:
          - xxx-service
test:
  config1: 123
---
spring:
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:classpath:test.yml
    activate:
      on-profile: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
#      server-addr: "[::]:8848"
      config:
        file-extension: yml
      discovery:
        namespace: 111
        service: ${spring.application.name}
      server-addr: localhost:8848
    loadbalancer:
      eager-load:
        clients:
          - xxx-service
test:
  config1: 456


