spring:
  application:
    name: last-cloud
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      config:
        preference: remote
nacos:
  server:
    aaLong: "{a : 'b'}" # value使用map必须使用这种, @Value不建议复杂类型, 建议使用@ConfigurationProperties
